fix failure in grep

diff --git a/Scripts/Check b/Scripts/Check
--- a/Scripts/Check
+++ b/Scripts/Check
@@ -8,13 +8,14 @@ cd repositories
 repository=${1##*/}
 
 if [ ! -d "$repository" ]; then
-    git clone "https://github.com/$1"
+    git clone -q "https://github.com/$1"
 fi
 
 cd "$repository"
 
-insecure_emails_author=$(git log --format="%ae" | grep "@gmail.com" | sort -u | wc -l)
-insecure_emails_committer=$(git log --format="%ce" | grep "@gmail.com" | sort -u | wc -l)
+# if there are no emails, grep will also fail, which is why coalescence is needed
+insecure_emails_author=$(git log --format="%ae" | grep "@gmail.com" | sort -u | wc -l || true)
+insecure_emails_committer=$(git log --format="%ce" | grep "@gmail.com" | sort -u | wc -l || true)
 
 if [ $insecure_emails_author -ne "0" ]; then
     echo "found ${insecure_emails_author} insecure author email addresses in repo '${repository}'!"
diff --git a/Scripts/CheckAll b/Scripts/CheckAll
--- a/Scripts/CheckAll
+++ b/Scripts/CheckAll
@@ -7,7 +7,16 @@ readarray -t organization < \
     <(gh repo list rarestype --source --json nameWithOwner -q '.[].nameWithOwner')
 readarray -t additional < Scripts/AdditionalRepositories
 
-for id in "${organization[@]}" "${additional[@]}"; do
-    echo "validating repo '${id}'"
-    Scripts/Check "$id"
+any_failed=0
+
+for id in "${organization[@]}"; do
+    if ! Scripts/Check "$id"; then
+        echo "Check failed for $id!"
+        any_failed=1
+    fi
 done
+
+if [ "$any_failed" -ne 0 ]; then
+    echo "One or more repositories contains insecure emails!"
+    exit 1
+fi
